
package com.davydov.corridorsgametwo.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameServerService", targetNamespace = "http://server.corridorsgametwo.davydov.com/", wsdlLocation = "http://localhost:8080/GameServer?wsdl")
public class GameServerService
    extends Service
{

    private final static URL GAMESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMESERVERSERVICE_EXCEPTION;
    private final static QName GAMESERVERSERVICE_QNAME = new QName("http://server.corridorsgametwo.davydov.com/", "GameServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GameServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMESERVERSERVICE_WSDL_LOCATION = url;
        GAMESERVERSERVICE_EXCEPTION = e;
    }

    public GameServerService() {
        super(__getWsdlLocation(), GAMESERVERSERVICE_QNAME);
    }

    public GameServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMESERVERSERVICE_QNAME, features);
    }

    public GameServerService(URL wsdlLocation) {
        super(wsdlLocation, GAMESERVERSERVICE_QNAME);
    }

    public GameServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMESERVERSERVICE_QNAME, features);
    }

    public GameServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameServer
     */
    @WebEndpoint(name = "GameServerPort")
    public GameServer getGameServerPort() {
        return super.getPort(new QName("http://server.corridorsgametwo.davydov.com/", "GameServerPort"), GameServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameServer
     */
    @WebEndpoint(name = "GameServerPort")
    public GameServer getGameServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.corridorsgametwo.davydov.com/", "GameServerPort"), GameServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMESERVERSERVICE_EXCEPTION!= null) {
            throw GAMESERVERSERVICE_EXCEPTION;
        }
        return GAMESERVERSERVICE_WSDL_LOCATION;
    }

}
