
package com.davydov.corridorsgametwo.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameServer", targetNamespace = "http://server.corridorsgametwo.davydov.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameServer {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "onAddNewSymbol", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnAddNewSymbol")
    @ResponseWrapper(localName = "onAddNewSymbolResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnAddNewSymbolResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onAddNewSymbolRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onAddNewSymbolResponse")
    public void onAddNewSymbol(
        @WebParam(name = "arg0", targetNamespace = "")
        AddNewSymbol arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "onConnectToGameServer", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnConnectToGameServer")
    @ResponseWrapper(localName = "onConnectToGameServerResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnConnectToGameServerResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onConnectToGameServerRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onConnectToGameServerResponse")
    public String onConnectToGameServer();

    /**
     * 
     * @return
     *     returns com.davydov.corridorsgametwo.webservice.StartGame
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "onStartGame", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnStartGame")
    @ResponseWrapper(localName = "onStartGameResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnStartGameResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onStartGameRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onStartGameResponse")
    public StartGame onStartGame();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.davydov.corridorsgametwo.webservice.AddNewBorder>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "onGetNewBorders", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnGetNewBorders")
    @ResponseWrapper(localName = "onGetNewBordersResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnGetNewBordersResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onGetNewBordersRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onGetNewBordersResponse")
    public List<AddNewBorder> onGetNewBorders(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.davydov.corridorsgametwo.webservice.AddNewSymbol>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "onGetNewSymbols", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnGetNewSymbols")
    @ResponseWrapper(localName = "onGetNewSymbolsResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnGetNewSymbolsResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onGetNewSymbolsRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onGetNewSymbolsResponse")
    public List<AddNewSymbol> onGetNewSymbols(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "onGetPlayerMove", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnGetPlayerMove")
    @ResponseWrapper(localName = "onGetPlayerMoveResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnGetPlayerMoveResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onGetPlayerMoveRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onGetPlayerMoveResponse")
    public String onGetPlayerMove();

    /**
     * 
     * @return
     *     returns com.davydov.corridorsgametwo.webservice.StopGame
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "onCheckEndGame", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnCheckEndGame")
    @ResponseWrapper(localName = "onCheckEndGameResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnCheckEndGameResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onCheckEndGameRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onCheckEndGameResponse")
    public StopGame onCheckEndGame();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "onAddNewBorder", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnAddNewBorder")
    @ResponseWrapper(localName = "onAddNewBorderResponse", targetNamespace = "http://server.corridorsgametwo.davydov.com/", className = "com.davydov.corridorsgametwo.webservice.OnAddNewBorderResponse")
    @Action(input = "http://server.corridorsgametwo.davydov.com/GameServer/onAddNewBorderRequest", output = "http://server.corridorsgametwo.davydov.com/GameServer/onAddNewBorderResponse")
    public void onAddNewBorder(
        @WebParam(name = "arg0", targetNamespace = "")
        AddNewBorder arg0);

}
